"""
Streamlit chat interface for the astrologer model.

Usage:
    streamlit run streamlit_app.py
    streamlit run streamlit_app.py -- --model Qwen/Qwen2.5-3B-Instruct

Memory: < 200 MB (UI only, model loaded at first user message).
"""

import argparse
import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).parent))

from src.inference.engine import InferenceEngine
from src.inference.chat import Conversation

# Page config
st.set_page_config(
    page_title="Vedaz Astrologer Chat",
    page_icon="\u2b50",
    layout="centered",
)

# Parse args
parser = argparse.ArgumentParser()
parser.add_argument("--model", type=str, default="Qwen/Qwen2.5-3B-Instruct")
parser.add_argument("--no-vllm", action="store_true")
args, _ = parser.parse_known_args()


# ---------- Session state ----------
if "chat" not in st.session_state:
    st.session_state.chat = Conversation(
        system_prompt=(
            "You are Vedaz's AI Vedic astrologer. You give compassionate, "
            "balanced, non-fatalistic guidance. You never predict death, "
            "illness, or guaranteed misfortune. Respond in the user's language."
        )
    )
if "engine" not in st.session_state:
    st.session_state.engine = None
if "messages" not in st.session_state:
    st.session_state.messages = []


# ---------- Title ----------
st.title("\u2b50 Vedaz Astrologer")
st.caption("Vedic astrology guidance — compassionate, balanced, non-fatalistic")


# ---------- Load engine ----------
@st.cache_resource
def load_engine(model_path: str, no_vllm: bool):
    return InferenceEngine(
        model_path=model_path,
        use_vllm=not no_vllm,
    )


# ---------- Display chat history ----------
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# ---------- Chat input ----------
if prompt := st.chat_input("Ask the astrologer..."):
    # Load engine on first message
    if st.session_state.engine is None:
        with st.spinner("Loading model (first time only)..."):
            st.session_state.engine = load_engine(args.model, args.no_vllm)

    # Display user message
    with st.chat_message("user"):
        st.markdown(prompt)
    st.session_state.messages.append({"role": "user", "content": prompt})

    # Add to conversation history
    st.session_state.chat.add_user(prompt)

    # Generate response
    with st.chat_message("assistant"):
        with st.spinner("Analyzing..."):
            response = st.session_state.engine.generate(
                messages=st.session_state.chat.messages,
                max_new_tokens=512,
                temperature=0.7,
            )
        st.markdown(response)

    st.session_state.messages.append({"role": "assistant", "content": response})
    st.session_state.chat.add_assistant(response)
    st.session_state.chat.trim_to_last_n_turns(5)


# ---------- Sidebar ----------
with st.sidebar:
    st.header("About")
    st.markdown(
        "This AI astrologer provides Vedic astrology insights based on "
        "your birth chart. Responses are generated by a fine-tuned language model "
        "trained on astrologer conversations.\n\n"
        "**Note:** Astrology readings are for guidance and entertainment. "
        "Always consult qualified professionals for medical, legal, or financial decisions."
    )

    if st.button("Clear conversation"):
        st.session_state.chat.clear()
        st.session_state.messages = []
        st.rerun()

    st.divider()
    st.caption(f"Model: {args.model}")
